Fix compilation issues introduced by SVN r4424
SVN r4424 / 9bdbdfa9501743b5f178a5a04b61deeccec54ea8 introduced several
issues:

- Changed interface (cache_block_closing) needs to be adjusted for PPC
  and PPC64, as upstream does not support these architectures. It seems
  like change from pointer to const pointer here is temporary WIP on SVN
  trunk (because it does not make sense, considering code below needs to
  const_cast back to normal pointer anyway), so avoid porting additional
  implementation to PPC/PPC64 dynrec backends for now.

- That commit straight does not compile with dynrec backend turned on
  and debugger feature turned on, the error is:

  error: invalid operands of types 'Bit64u' {aka 'long unsigned int'}
         and 'const Bit8u*' {aka 'const unsigned char*'} to binary
         'operator-'

  Adjust the code to address the issue by replacing Bit64s with more
  appropriate, standard (signed) ptrdiff_t for calculating pointer
  difference.