Move libSDL2_net ahead of SDL2 and both behind common LIBSs
This fixes a link-order regression caught in Config Heavy's CI build
enabling static SDL2 linking under Windows.

The issue:

-Wl,--as-needed -static-libgcc
-static-libstdc++ -Wl,-Bstatic -lSDL2_net <-- SDL2_net needs to come
-Wl,-Bdynamic -L/mingw64/lib -lmingw32        before SDL2, but after
-ldxerr8 -ldinput8 -lshell32 -lsetupapi       all of these lower-
-ladvapi32 -luuid -lversion -loleaut32        level libaries.
-lole32 -limm32 -lwinmm -lgdi32 -luser32
-lm -Wl,--no-undefined -pipe -lmingw32
-lSDL2main -lSDL2 -mwindows
-LC:/tools/msys64/mingw64/lib -lpng16 -lz
-lz -LC:/tools/msys64/mingw64/lib
-lopusfile -lopengl32 -lwinmm -lws2_32

Results in:
  undefined reference to `GetAdaptersInfo'