Workaround bug introduced in the ncurses MSYS2 packages
Revert-when-fixed.

Flagged by @shermp in https://github.com/msys2/MINGW-packages/issues/10312

Causes link errors, as follows:

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x10): undefined reference to `__imp_initscr'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x23): undefined reference to `__imp_printw'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x2c): undefined reference to `__imp_stdscr'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x39): undefined reference to `__imp_wrefresh'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x42): undefined reference to `__imp_stdscr'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x4f): undefined reference to `__imp_wgetch'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccCrSAYo.o:ncurses.c:(.text+0x58): undefined reference to `__imp_endwin'

collect2.exe: error: ld returned 1 exit status

Co-authored-by: kcgen <1557255+kcgen@users.noreply.github.com>
Co-authored-by: shermp <14854761+shermp@users.noreply.github.com>