Move goto labels to prevent Clang errors
If there's a goto label between [[fallthrough]] statement and a
case label, Clang fails with:

error: fallthrough annotation does not directly precede switch label

GCC does not have a problem with this.